Documents/backend-research.md
- What we should expect from the backend
- How to get around CPanel limitation
Closes #3
=> feat(backend): Research doc

Code/node-src/package-lock.json, Code/node-src/package.json, README.md
Add dev-server for node, automatically builds & restarts the node application.
=> change(node): Add dev-server command

Code/react-src/src/App.tsx, Code/react-src/src/components/stakeholders/stakeholders.tsx, Code/react-src/src/index.css
This contains most of the front end for the stakeholder page
=> Stakeholder layout

Code/node-src/app/index.ts, Code/node-src/package-lock.json, Code/node-src/package.json, Code/node-src/tests/example.test.ts, Code/react-src/package-lock.json, Code/react-src/package.json, Code/react-src/src/App.tsx, Code/react-src/src/components/functional-components/privateroute.component.tsx, Code/react-src/src/components/home/home.tsx, Code/react-src/src/components/login/login.tsx, Code/react-src/src/helpers/http.ts, Code/react-src/src/index.css, Code/react-src/src/services/account.service.ts, Code/react-src/src/stores/main.d.ts, Code/react-src/src/stores/main.store.ts, Code/react-src/src/types/index.d.ts
=> Add store provider, basic login page & route

Code/node-src/app/controllers/account.controller.ts, Code/node-src/app/models/account.model.ts, Code/node-src/app/routes/account.routes.ts, Code/node-src/tests/example.test.ts, Code/react-src/src/App.tsx, Code/react-src/src/components/login/login.tsx, Code/react-src/src/components/register/register.tsx, Code/react-src/src/index.css, Code/react-src/src/services/account.service.ts, Code/react-src/src/stores/main.d.ts, Code/react-src/src/stores/main.store.ts, Code/react-src/src/types/index.d.ts
=> feat(react): Add register page and account creation

Code/react-src/src/App.tsx, Code/react-src/src/components/account/myaccount.tsx, Code/react-src/src/components/functional-components/privateroute.component.tsx
Basic information shown to user, can be extended in future to allow account management.
=> feat(react): Add basic my account page

Documents/ClientMeetingNotes/ClientMeetingNotes-11-24.txt
=> Add client notes for 24/11

Code/react-src/src/App.tsx, Code/react-src/src/components/deontology/deontology-options.tsx, Code/react-src/src/components/utilitarianism/utilitarianism-pleasure.tsx, Code/react-src/src/styles/main.css
=> Added start to first page of Deontology

Code/react-src/src/App.tsx, Code/react-src/src/components/dashboard-home/dashboard-home.tsx
Created a first version of the layout of the main dashboard.  Link to the other current pages have also been made.
=> DashboardCSS

Code/node-src/app/controllers/account.controller.ts, Code/node-src/app/controllers/dashboard.controller.ts, Code/node-src/app/index.ts, Code/node-src/app/middleware/authorize.ts, Code/node-src/app/models/account/account.model.ts, Code/node-src/app/models/dashboard.model.ts, Code/node-src/app/routes/dashboard.routes.ts, Code/node-src/package-lock.json, Code/node-src/package.json, Code/node-src/tests/classgroup.test.ts, Code/node-src/tests/dashboard.test.ts, Code/node-src/tests/tsconfig.json, Code/node-src/tsconfig.json, Code/node-src/types/index.d.ts, Code/react-src/src/services/account.service.ts, Code/react-src/src/stores/account.store.ts
- Improved the Request object to include account info.
- Added basic Dashboard backend
=> Improve types, add initial Dashboard controller

Code/node-src/app/app.ts, Code/node-src/app/index.ts, Code/node-src/jest.config.js, Code/node-src/tests/account.test.ts, Code/node-src/tests/classgroup.test.ts, Code/node-src/tests/dashboard.test.ts, Code/node-src/tests/example.test.ts, Code/node-src/tests/setup.ts
Add test accounts: 
- Username: `user`, Password:  `user`
- Username: `admin`, Password: `admin`
Also fixes running the `npm run dev-server` command.
- Includes small test refactor
=> feat(node): Add test accounts

Code/node-src/app/database.ts, Code/node-src/app/models/care_ethics_options.model.ts, Code/node-src/app/models/deontology_categorical.model.ts, Code/node-src/app/models/option.model.ts, Code/node-src/app/models/stakeholder.model.ts, Code/node-src/app/models/util_opt_analysis.model.ts, Code/node-src/app/models/utilitarianism.model.ts
getting the main structure of models created
=> Models First Pass

Code/react-src/src/components/care/care-ethics.tsx, Code/react-src/src/components/care/option-care-ethics-input.tsx, Code/react-src/src/components/care/stakeholder-care-ethics-input.tsx, Code/react-src/src/components/utilitarianism/options-pleasure-output.tsx, Code/react-src/src/components/utilitarianism/stakeholder-pleasure-input.tsx, Code/react-src/src/components/utilitarianism/utilitarianism-pleasure.tsx, Code/react-src/src/styles/main.css
Close #127 
Completed code for average sliders for Utilitarianism and Care Ethics pages
=> (feat) Sliders Average

Code/node-src/package-lock.json, Code/react-src/package-lock.json, Code/react-src/package.json, Code/react-src/src/App.tsx, Code/react-src/src/components/virtueEthics/VirtueEthics-BallBalanced.tsx, Code/react-src/src/components/virtueEthics/virtueEthics-Character.tsx, Code/react-src/src/components/virtueEthics/virtueEthics-RankBalance.tsx, Code/react-src/src/components/virtueEthics/virtueEthics-Stakeholders.tsx, Code/react-src/src/components/virtueEthics/virtueEthicsProps/virtueEthics-ballProps.tsx, Code/react-src/src/components/virtueEthics/virtueEthicsProps/virtueEthics-characterInputs.tsx, Code/react-src/src/components/virtueEthics/virtueEthicsProps/virtueEthics-stakeholderInputs.tsx, Code/react-src/src/styles/main.css
Still some finishing touches left as things are hard-coded in areas. The drag is done with the draggable API, as many of the other things I tried weren't working how I wanted them to. The draggable API needs to have the command 
npm install react-draggable
in react-src. There is also some implementation stuff on it [here](https://www.npmjs.com/package/react-draggable)
I would like to add a grid system to it so things snap properly, but need to do more research into that as I could not get it working like that yet today.
=> VirtueEthicsComplete

Code/react-src/src/components/account/editprofile.tsx, Code/react-src/src/components/account/myaccount.tsx, Code/react-src/src/components/global/button.tsx, Code/react-src/src/components/global/form.tsx, Code/react-src/src/components/global/forminput.tsx, Code/react-src/src/components/home/dashboards.tsx, Code/react-src/src/components/home/home.tsx, Code/react-src/src/components/navbar.tsx, Code/react-src/src/helpers/http.ts, Code/react-src/src/services/account.service.ts, Code/react-src/src/stores/account.store.ts, Code/react-src/src/styles/main.css, Code/react-src/tailwind.config.js
- Currently not hooked up to DB, need to merge this PR and then work on Ben's branch.
=> Feat: Homepage adjustments, color palette change, and profile changes

Code/react-src/src/components/Issues/Issues.tsx, Code/react-src/src/components/care/care-ethics.tsx, Code/react-src/src/components/care/option-care-ethics-input.tsx, Code/react-src/src/components/care/stakeholder-care-ethics-input.tsx, Code/react-src/src/components/dashboard-home/dashboard-home.tsx, Code/react-src/src/components/deontology/deontology-categorical.tsx, Code/react-src/src/components/deontology/deontology-hypothetical.tsx, Code/react-src/src/components/deontology/deontology-moral-law.tsx, Code/react-src/src/components/deontology/deontology-options-input.tsx, Code/react-src/src/components/deontology/deontology-options.tsx, Code/react-src/src/components/deontology/deontology-testing-categorical.tsx, Code/react-src/src/components/global/stakeholderform.tsx, Code/react-src/src/components/global/stakeholderinput.tsx, Code/react-src/src/components/login/login.tsx, Code/react-src/src/components/my-progress/my-progress-report.tsx, Code/react-src/src/components/stakeholders/stakeholders.tsx, Code/react-src/src/components/utilitarianism/options-pleasure-output.tsx, Code/react-src/src/components/utilitarianism/stakeholder-pleasure-input.tsx, Code/react-src/src/components/utilitarianism/utilitarianism-options.tsx, Code/react-src/src/components/utilitarianism/utilitarianism-pleasure.tsx, Code/react-src/src/components/utilitarianism/utilitarianism-stakeholders.tsx, Code/react-src/src/components/virtueEthics/VirtueEthics-Ball.tsx, Code/react-src/src/components/virtueEthics/VirtueEthics-BallBalanced.tsx, Code/react-src/src/components/virtueEthics/virtueEthics-Character.tsx, Code/react-src/src/components/virtueEthics/virtueEthics-RankBalance.tsx, Code/react-src/src/components/virtueEthics/virtueEthics-Stakeholders.tsx, Code/react-src/src/components/virtueEthics/virtueEthicsProps/virtueEthics-characterInputs.tsx, Code/react-src/src/components/virtueEthics/virtueEthicsProps/virtueEthics-stakeholderInputs.tsx, Code/react-src/src/styles/main.css, Code/react-src/tailwind.config.js
Close #123 
Refactored the designs for all the pages so we can reuse styles. This was done based on peer-testing feedback
=> (chore) Design refactor

Code/react-src/src/App.tsx, Code/react-src/src/components/Issues/Issues.tsx, Code/react-src/src/components/utilitarianism/options-summary-output.tsx, Code/react-src/src/components/utilitarianism/utilitarianism-summary.tsx
Close #54 
Completed implementation for Utilitarianism Summary page
=> (feat) Utilitarianism Summary page

Code/react-src/package-lock.json, Code/react-src/package.json, Code/react-src/src/App.tsx, Code/react-src/src/components/account/myaccount.tsx, Code/react-src/src/components/home/dashboards.tsx, Code/react-src/src/components/register/register.tsx, Code/react-src/src/stores/account.store.ts
- Adds React Query to the frontend build.
- Adds some example usage of react query for mutation and fetching.
=> Feat: Init React Query and add basic examples

Code/react-src/src/App.tsx, Code/react-src/src/components/Issues/Issues.tsx, Code/react-src/src/components/home/dashboards.tsx
=> Feat: Add login check to all pages

Code/node-src/app/controllers/dashboard.controller.ts, Code/node-src/app/models/option.model.ts, Code/react-src/src/components/utilitarianism/utilitarianism-options-block.tsx, Code/react-src/src/components/utilitarianism/utilitarianism-options.tsx, Code/react-src/src/stores/index.store.ts, Code/react-src/src/stores/option.store.ts
Utilitarianism consequences are now updating to the database
=> Feat backend utilitarianism

Code/node-src/app/controllers/account.controller.ts, Code/node-src/app/models/account/account.model.ts, Code/node-src/app/routes/account.routes.ts, Code/react-src/src/components/account/editprofile.tsx, Code/react-src/src/components/account/myaccount.tsx, Code/react-src/src/components/dashboard-home/stakeholders.tsx, Code/react-src/src/components/global/forminput.tsx, Code/react-src/src/components/navbar.tsx, Code/react-src/src/services/account.service.ts, Code/react-src/src/stores/account.store.ts
- Adds avatar saving to the database and updates the account when uploaded
=> Feat: Account avatar uploading
